spotless, shell expansions
Signed-off-by: Andrew Brandt <andrew.brandt@hashgraph.com>

diff --git a/.github/workflows/node-zxc-deploy-preview.yaml b/.github/workflows/node-zxc-deploy-preview.yaml
--- a/.github/workflows/node-zxc-deploy-preview.yaml
+++ b/.github/workflows/node-zxc-deploy-preview.yaml
@@ -96,15 +96,15 @@ jobs:
       - name: Verify Version Update (As Specified)
         if: ${{ inputs.version-policy == 'specified' && !cancelled() && !failure() }}
         run: |
-          if [[ "$(semver validate "$VERSION" 2>/dev/null || echo "invalid")" == "valid" ]]; then
-            VALID_VERSION="true"
-          fi
-          
-          if [[ "$VERSION" =~ ^build-[0-9]+$ ]]; then
+          if [[ "$(semver validate "${VERSION}" 2>/dev/null || echo "invalid")" == "valid" ]]; then
             VALID_VERSION="true"
           fi
 
-          if [[ "$VALID_VERSION" != "true" ]]; then
+          if [[ "${VERSION}" =~ ^build-[0-9]+$ ]]; then
+            VALID_VERSION="true"
+          fi
+
+          if [[ "${VALID_VERSION}" != "true" ]]; then
             echo "::error title=Version Error::The supplied new-version parameter (${{ inputs.new-version }}) is invalid and does not conform to the semantic versioning specifications."
             exit 2
           else
