updated the longevity workflow to run SDCT
Signed-off-by: Tom Zheng <tom.zheng@swirldslabs.com>

diff --git a/.github/workflows/zxf-single-day-longevity-test.yaml b/.github/workflows/zxf-single-day-longevity-test.yaml
--- a/.github/workflows/zxf-single-day-longevity-test.yaml
+++ b/.github/workflows/zxf-single-day-longevity-test.yaml
@@ -16,17 +16,16 @@ on:
 
 defaults:
   run:
-    shell: bash
+    shell: bash -euo pipefail {0}
 
 jobs:
   canonical-test:
     name: Canonical
     runs-on: hiero-citr-linux-medium
-    timeout-minutes: 60  # max one hour timeout 
 
     permissions:
-      id-token: write
       contents: read
+      id-token: write
 
     steps:
       - name: Harden Runner
@@ -54,38 +53,10 @@ jobs:
         uses: google-github-actions/setup-gcloud@77e7a554d41e2ee56fc945c52dfd3f33d12def9a # v2.1.4
         with:
           version: 'latest'
-          install_components: 'gsutil'
+          install_components: "gsutil"
 
-     - name: Install Utility Tools
-        run: |
-          if ! command -v jq >/dev/null 2>&1; then
-            echo "::group::Setup JQ Command"
-            sudo apt update
-            sudo apt install -y jq
-            echo "::endgroup::"
-          fi
-          JQ_VERSION="$(jq --version)"
-          if [[ "${JQ_VERSION}" != "jq-1.6" ]]; then
-            echo "::group::Updating JQ Version"
-            sudo apt update
-            sudo apt upgrade -y jq
-            echo "::endgroup::"
-          fi
-          if ! command -v tee >/dev/null 2>&1; then
-            echo "::group::Setup Tee Command"
-            sudo apt update
-            sudo apt install -y coreutils
-            echo "::endgroup::"
-          fi
-          if ! command -v curl >/dev/null 2>&1; then
-            echo "::group::Setup Curl Command"
-            sudo apt update
-            sudo apt install -y curl
-            echo "::endgroup::"
-          fi
-          echo "::group::Show JQ Version"
-          jq --version
-          echo "::endgroup::"
+      - name: Install Utility Tools
+        run: sudo apt update && sudo apt install -y jq curl
 
       - name: Verify Workflow Parameters
         id: parameters
@@ -98,24 +69,24 @@ jobs:
             BRANCH_NAME_LOWER="$(echo "${BRANCH_NAME}" | tr '[:upper:]' '[:lower:]')"
             BRANCH_NAME_SAFE="$(echo "${BRANCH_NAME_LOWER}" | tr '/_' '-.')"
             TAG_COMMIT_SHA=$(git rev-list -n 1 "${BUILD_ARTIFACT}") || {
-              echo "❌ Error : Tag ${BUILD_ARTIFACT} not found"
+              echo "❌ Error: Tag ${BUILD_ARTIFACT} not found" >&2
               exit 1
             }
             TAG_COMMIT_SHORT="${TAG_COMMIT_SHA:0:8}"
             BUILD_ARTIFACT="build-${BRANCH_NAME_SAFE}-${TAG_COMMIT_SHORT}"
           fi
           echo "artifact-name=${BUILD_ARTIFACT}" >> "${GITHUB_OUTPUT}"
-          echo "Artifact name: ${BUILD_ARTIFACT}"
 
-      - name: Check If Release Artifact Exist in Bucket
+      - name: Check Artifact Availability
         id: check-if-exist
+        timeout-minutes: 60  # max one hour timeout 
         run: |
           set -euo pipefail
 
           ARTIFACT_NAME="${{ steps.parameters.outputs.artifact-name }}"
           BUCKET_NAME="${{ secrets.RELEASE_ARTIFACT_BUCKET_NAME }}"
           if [[ -z "${ARTIFACT_NAME}" ]]; then
-            echo "❌ Error : Artifact name is empty"
+            echo "❌ Error: Artifact name is empty"
             exit 1
           fi
           if [[ -z "${BUCKET_NAME}" ]]; then
@@ -126,17 +97,12 @@ jobs:
           ARTIFACT_PATH="gs://${BUCKET_NAME}/${ARTIFACT_NAME}.zip"
           echo "ARTIFACT_PATH=${ARTIFACT_PATH}"
 
-          while true
-          do
-            gsutil -q stat "${ARTIFACT_PATH}"
-            PATH_EXIST=$?
-            if [ ${PATH_EXIST} -eq 0 ]; then
-              break
-            else
-              echo "⏳ Artifact ${ARTIFACT_NAME}.zip not ready, wait for 2 minutes."
-              sleep 2m
-            fi
+          for ((i=1;i<=30;i++)); do
+              gsutil -q stat "${ARTIFACT_PATH}" && break
+              echo "⏳ Artifact ${ARTIFACT_NAME}.zip not ready, wait for 2 minutes, on [$i/30] try." ; sleep 120
           done
+          ((i<=30)) || { echo "❌ Error: Artifact not found after 30 attempts, timed out."; exit 1; }
+
           echo "✅ Artifact ${ARTIFACT_NAME}.zip is available."
           echo "build-tag=${{ inputs.build-tag }}" >> "${GITHUB_OUTPUT}"
           echo "build-version=${ARTIFACT_NAME}" >> "${GITHUB_OUTPUT}"
@@ -151,7 +117,6 @@ jobs:
 
         run: |
           bash "${{ github.workspace }}/${{ env.TEST_SCRIPT }}" \
-               "${{ env.USERNAME }}" "${{ env.PASSWORD }}" "${{ env.SERVER }}" \
                "${{ steps.check-if-exist.outputs.build-tag }}" \
                "${{ steps.check-if-exist.outputs.build-version }}" 
 
